project:
  type: book
  # LuaLaTeX fonts are often broken on NixOS
  pre-render: luaotfload-tool --cache=erase --flush-lookups --force
  post-render: rm -f SCI_(black).pdf MUNI_(black).pdf sci.muni.thesis.sty fonts.html thesis.scss

book:
  title: "Computational analysis in neuroscience"
  author:
    - name: Štěpán Zapadlo
      orcid: 0009-0008-7823-6239
      email: stepan@zapadlo.name
      affiliations: Masaryk University
  chapters:
    - text: "Front matter"
      file: index.qmd
    - "introduction.qmd"
    - "general-theory.qmd"
    - "refs.qmd"
  sidebar:
    style: "docked"

  repo-url: https://github.com/sceptri/masters-thesis
  repo-actions: [edit, source, issue] # TODO: For Codeberg hopefully will be fixed soon (or will probably need to use a custom Quarto with some patch)

  license: MIT
  page-footer:
    right: 
      - text: "License"
        href: LICENSE

  downloads: [pdf]

bibliography: bibliography.bib

thesis:
  coloring: Barevne # Barevne | Tisk
  type: Mgr # Bc | Mgr | RNDr
  degree: "Master's"
  submitted: 2025
  academic-year: 2024/2025
  affiliation: 
    university: Masaryk University
    location: Brno
    cz: Ústav matematiky a statistiky
    en: Department of Mathematics and Statistics
  title:
    cz: Computational analysis in neuroscience
    bookmarks: Computational analysis in neuroscience
    en: Computational analysis in neuroscience
  supervisor: doc. RNDr. Lenka Přibylová, Ph.D.
  studies:
    program:
      cz: Matematika
      en: Mathematics
    field:
      cz: Modelování a výpočty
      en: Modelling and computations
  keywords:
    cz: "Práce; Něco; Klíčové slovo" # TODO: Do this
    en: "Thesis; Keyword; Long word" # TODO: Do this
  page-count: "xv + 91" # TODO: Try and remove this...
  abstract:
    cz: "partials/abstrakt.qmd"
    en: "partials/abstract.qmd"
  acknowledgement: 
    cz: "partials/podekovani.qmd"
    en: "partials/acknowledgement.qmd"
  declaration: 
    cz: "partials/prohlaseni.qmd"
    en: "partials/declaration.qmd"
    date: 24.09.2024 # FIXME: Something like `last-modified`
  assignment: "assets/assignment.pdf" # TODO: Change name

format:
  munithesis-html:
    mainfont: Merriweather # Use et-book instead: https://github.com/edwardtufte/et-book

    toc: true
    toc-expand: 3

    header-includes: |
      <link rel="preconnect" href="https://fonts.googleapis.com">
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
      <link href="https://fonts.googleapis.com/css2?family=Merriweather:ital,wght@0,300;0,400;0,700;0,900;1,300;1,400;1,700;1,900&family=Tinos:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet">
  munithesis-pdf:
    mainfont: "Tex Gyre Pagella" # Maybe fix xelatex compilation?
    mathfont: "TeX Gyre Pagella Math"
    monofont: "TeX Gyre Cursor" # or Latin Modern Mono

    keep-tex: false
    hyperrefoptions:
      - hyperfootnotes=false
    include-in-header:
      - mathematics/pdf.tex
      - mathematics/general.tex
      - mathematics/analysis.tex
      - mathematics/linear-algebra.tex
      - mathematics/statistics.tex
      - mathematics/distributions.tex
      - mathematics/special.tex
      - mathematics/overrides.tex

    toc: true
    number-sections: true

    fig-align: center
    fig-pos: H
    
    fig-format: png
    mermaid-format: png
    df-print: tibble
filters:
 - munithesis

profiles:
  default: basic