# Algorithms

:::{.hidden}
{{< include mathematics.qmd >}}
:::

::: {.callout appearance="simple" #alg-golden-section-method}
##### Golden section method
**Input:** Optimization problem ([-@eq-unimodal-optim-problem]), initial interval $I = [a,b]$, number of evaluations $N \in \N$ \
**Output:** Approximation of minimum $\bar{x}_k$ \
**begin** \
&emsp;&emsp;set $[a_0, b_0] \gets [a,b]$, $l_0 \gets b_0 - a_0$; \
&emsp;&emsp;calculate $x_2^- \gets a_0 + \frac 1 {\goldRatio^2} l_0$ & $x_2^+ \gets a_0 + \frac 1 \goldRatio l_0$; \
&emsp;&emsp;evaluate $f_2^- \gets f(x_2^-)$, $f_2^+ \gets f(x_2^+)$ \
&emsp;&emsp;**if** $f_2^- < f_2^+$ **do** \
&emsp;&emsp;&emsp;&emsp;set $[a_2, b_2] \gets [a_0, x_2^+]$; \
&emsp;&emsp;&emsp;&emsp;set $\mathrm{Increasing} \gets 1$; \
&emsp;&emsp;**else do** \
&emsp;&emsp;&emsp;&emsp;set $[a_2, b_2] \gets [x_2^-, b_0]$; \
&emsp;&emsp;&emsp;&emsp;set $\mathrm{Increasing} \gets 0$; \
&emsp;&emsp;**end** \
&emsp;&emsp;set $l_2 \gets b_2 - a_2$ \
&emsp;&emsp;**for** $i = 3$ **to** $N$ **do** \
&emsp;&emsp;&emsp;&emsp;**if** $\mathrm{Increasing}$ equals $1$ **do** \
&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;set $x_i^+ \gets x_{i-1}^-$, $f_i^+ = f_{i-1}^-$; \
&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;calculate $x_i^- \gets a_{i-1} + \frac 1 {\goldRatio^2} l_{i-1}$; \
&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;evaluate $f_i^- \gets f(x_i^-)$ \
&emsp;&emsp;&emsp;&emsp;**else do** \
&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;set $x_i^- \gets x_{i-1}^+$, $f_i^- = f_{i-1}^+$; \
&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;calculate $x_i^+ \gets a_{i-1} + \frac 1 {\goldRatio} l_{i-1}$; \
&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;evaluate $f_i^+ \gets f(x_i^+)$ \
&emsp;&emsp;&emsp;&emsp;**end** \
&emsp;&emsp;&emsp;&emsp;**if** $f_i^- < f_i^+$ **do** \
&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;set $[a_i, b_i] \gets [a_{i-1}, x_i^+]$; \
&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;set $\mathrm{Increasing} \gets 1$; \
&emsp;&emsp;&emsp;&emsp;**else do** \
&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;set $[a_i, b_i] \gets [x_i^-, b_{i-1}]$; \
&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;set $\mathrm{Increasing} \gets 0$; \
&emsp;&emsp;&emsp;&emsp;**end** \
&emsp;&emsp;&emsp;&emsp;set $l_i \gets b_i - a_i$; \
&emsp;&emsp;&emsp;&emsp;set $\bar{x}_i \gets \frac {a_i + b_i} 2$ \
&emsp;&emsp;**end** \
**end**
:::

::: {.callout appearance="simple" #alg-fibonacci-method}
##### Fibonacci method
**Input:** Optimization problem ([-@eq-unimodal-optim-problem]), initial interval $I = [a,b]$, number of evaluations $N \in \N$, tolerance $\ve > 0$ small \
**Output:** Approximation of minimum $\bar{x}$ \
**begin** \
&emsp;&emsp;set $A \gets a$, $B \gets b$, $n \gets N$; \
&emsp;&emsp;define $s \letDef \frac {1 - \sqrt{5}} {1 + \sqrt{5}}$; \
&emsp;&emsp;let $\rho \gets \frac 1 {\goldRatio} \frac {1 - s^n}{1 - s^{n+1}}$, $r \gets (1 - \rho) A + \rho B$; \
&emsp;&emsp;set $f^r \gets f(r)$ and $n \gets n - 1$ \
&emsp;&emsp;**while** $n > 0$ **do** \
&emsp;&emsp;&emsp;&emsp;**if** $n > 1$ **do** \
&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;set $l \gets \rho A + (1 - \rho) B$ \
&emsp;&emsp;&emsp;&emsp;**else do** \
&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;set $l \gets \ve A + (1 - \ve) r$ \
&emsp;&emsp;&emsp;&emsp;**end** \
&emsp;&emsp;&emsp;&emsp;update $\rho \gets \frac 1 {\goldRatio} \frac {1 - s^n}{1 - s^{n+1}}$; \
&emsp;&emsp;&emsp;&emsp;set $f^l \gets f(l)$ and $n \gets n - 1$ \
&emsp;&emsp;&emsp;&emsp;**if** $f^l < f^r$ **do** \
&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;set $[r, B, f^r] \gets [l, r, f^l]$ \
&emsp;&emsp;&emsp;&emsp;**else do** \
&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;set $[A, B] \gets [B, l]$ \
&emsp;&emsp;&emsp;&emsp;**end** \
&emsp;&emsp;**end** \
&emsp;&emsp;set $\bar{x} = \frac {A + B} 2$ \
**end**
:::