:::{.content-visible when-format="pdf"}
\HeaderUnnumbered
:::

:::{.hidden}
{{< include mathematics.qmd >}}
:::

# Conclusions {#sec-conclusion .unnumbered}

Phase-locked synchronization is of utmost importance for neuroscience. Specifically, in-phase synchronization refers to the phase relationship between two coupled neurons firing simultaneously, whereas anti-phase synchronization refers to the phase relationship between two coupled neurons that maximizes the frequency of their combined signal. However, the problem of determining suitable parameter values, which would result in synchronization, and the phase shift thereof is a rather complicated task.

After building up the necessary theoretical background in the first chapter, we have delved into phase-shift detection using a grid simulation approach. Iteratively, we built and improved the methodology for the problem at hand, introducing various concepts along the way. Moreover, at each step, we applied the algorithm to a system of two weakly coupled interneuron models. Finally, the computation was executed on the MetaCentrum grid infrastructure.

In the third chapter, we discussed the localization of equilibria and limit cycles for both ODE and DDE systems. Then, we applied the showcased numerical methods to the system of interest, obtaining the cycle manifold corresponding to an Arnold tongue for a given synchronization. We were then able to compute phase shifts (between the two oscillators) of periodic orbits on the manifold. By projection to the parameter plane, we obtained a comparable result to the more traditional grid simulation.

It is rather complicated to say which method is "better", as each takes a very different route on the path to the same goal. The simulation-based approach more closely mimics (under the assumption of an appropriate *iterator*) a continuous change of parameters, which may or may not have the time to converge to the equilibrium. This renders the choice of transient interesting for applications because the method can compute synchronization modes the system can reach by continuously changing its parameters. Moreover, its strengths lie in the fact that much less theoretical background is needed, making it more accessible to a wider (academic) community.

Nevertheless, at its core, it is still a heuristic algorithm, which we have attempted to improve in various ways. Its biggest drawback probably lies in the dependence on nearby already computed trajectories and phase shifts for a given element of the grid. This very idea, which we have used to improve the Arnold tongue detection, complicates multi-threading execution and necessitates the use of a dense grid to allow us to draw reasonable conclusions. Lastly, while the initial draft of the method was rather easy to implement, each subsequent iteration makes it more complicated and introduces possible parameters and choices of methods/norms/etc. For instance, in the current version of *GridWalker.jl*, there are approximately 40 parameters/functions strictly related to the computation itself to be selected.

On the other hand, the approach based on bifurcation theory streamlines many parts of the process at the cost of much higher theoretical complexity of the underlying methods. Indeed, save for the shift computation, most of the algorithm uses standard continuation methods available in bifurcation toolkits, such as MATCONT or DDE-BIFTOOL. This also significantly reduces the number of parameters or selectable functions. Furthermore, the ability to easily and efficiently parallelize the computation compensates for the higher time complexity of the calculation at each individual point. Finally, the theoretical background and independence of single slice computation from the previous results guarantee that once we have computed a phase shift for a given point $(C_2^i, \lambda^i)$, it must hold for any discretization $\Lambda$ such that $\lambda^i \in \Lambda$. This crucial property is missing in the simulation-based approach. 

In total, we believe the bifurcation-based approach should be more prevalent in applied fields, as it offers clear computational benefits. Nevertheless, some capabilities of the grid simulation approach, for instance, stochastic phenomena or the effect of transient, cannot be replicated by using the continuation-based approach. Thus, researchers should strive to pick the best methodology for their problem of interest.