:::{.content-visible when-format="pdf"}
\HeaderUnnumbered
:::

:::{.hidden}
{{< include mathematics.qmd >}}
:::

# Introduction {#sec-intro .unnumbered}

:::{.content-visible when-format="pdf"}
:::{.callout-tip #tip-web-version}
##### Web version

This thesis is also available in [web version](https://thesis.uni.zapadlo.name/)^[[https://thesis.uni.zapadlo.name/](https://thesis.uni.zapadlo.name/)].
:::
:::

Synchronization is a phenomenon commonly found in nature and, as is often the case, it takes many shapes and forms. From the coordination between neurons in our brains or fire-fly lights to synchronization found in electrical grids and financial markets. What started in the 17th century with Huygens' investigation into the behavior of two weakly interacting pendulum clocks through a heavy beam, see @Willms2017, has since evolved into a field rich with both theory and applications.

The key application and motivation of this thesis lies, as the name may suggest, in physiological models of neurons in the brain. Several studies, see @Brazdil2023, @Cimbalnik2018, @Sevcik2025, @Pribylova2024, and @Pribylova2025 among others, have shown that fast to ultra-fast ripples (oscillations of frequencies ranging from 250 Hz to 2000 Hz, or even higher in the case of *ultra-fast oscillations*) in intracranial electroencephalographic (iEEG) recordings measured deep in the brain can be potentially used as biomarkers of epileptogenic zones of focal epilepsy. Furthermore, there is evidence they correlate with the severity of epilepsy. Research also suggests that very high-frequency oscillations (VHFOs) and ultra-fast oscillations (UFOs) are more local, i.e., spatially restricted than traditional biomarkers, high-frequency oscillations (HFOs), thus providing better guidance in locating the areas of epilepsy. Fast oscillations lie outside the realm of physiologically possible frequencies of single neurons. This indicates another mechanism must be at play, but its identification is an open question in neuroscience, see @Jiruska2017.

The primary goal of this thesis is to provide insight into a small part of computational analysis in neuroscience --- phase synchronization[^phase] of coupled neurons and techniques used in its detection and exploration. In particular, we will study two possible approaches and analyze their strengths and shortcomings.

[^phase]: By phase synchronization we mean the state when the difference in phase of the oscillators remains bounded while, e.g., their amplitudes may differ, see @Pikovsky2001.

Note that VFHOs and UFOs in the context of coupled neuronal models pose a very difficult problem from the point of view of applied mathematics. While in this thesis we only study numerical simulations of neuronal models, colleagues from the Nonlinear Dynamics team have explored the detection of VHFOs in EEG signals, see @Halastova2025. Moreover, the scope and focus of the thesis, i.e., computation of periods (frequencies) and shifts of simulated weakly coupled neuronal models, arose naturally as an extension of research conducted in the Nonlinear Dynamics team in the course of the GAMU Interdisciplinary project \# MUNI/G/1213/2022. This research direction was fueled by the necessity of understanding regions and types of synchrony of coupled neurons in the vicinity of an epileptogenic zone.

First and foremost, we shall introduce the necessary theory. Starting with a theoretical introduction to dynamical systems, we then shift our attention to delay differential equations and semidynamical systems induced by them. A discussion of methods of numerical integration for both ordinary and delay differential equations follows. Lastly, 1D optimization methods are studied, together with Newton's method, before shortly turning our attention to the models and principles from computational neuroscience.

In the second chapter, an approach for the computation of phase shift between two weakly coupled oscillators based on simulations of the corresponding differential equation is iteratively developed. Starting from a simple, naive algorithm, we progressively add various concepts to address present issues. We end this thesis by taking a different route and introducing the theory of localization of equilibria and periodic orbits. We then use these concepts from bifurcation theory to compute the phase shifts as continuations of cycles on a specific manifold.

Let us note the thesis is typeset using Quarto  @Quarto and all figures are generated in Julia @Bezanson2017 using the Makie.jl package @MakieJulia. Both HTML and PDF versions are available. All source code for this thesis (and included numerical computations) is included in the [Git repository]({{< meta book.repo-url >}})^[[{{< meta book.repo-url >}}]({{< meta book.repo-url >}})] (if not stated otherwise).